services:  
  jx-mysql:  
    image: mysql:8.0  
    env_file: .env 
    user: "1000:1000"
    volumes:  
      - mysql_data:/var/lib/mysql  
      - /mnt/pdm_shared/init-scripts:/docker-entrypoint-initdb.d:ro,Z
    environment:  
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?未设置根密码}  
      MYSQL_DATABASE: pdm_dev  
      MYSQL_USER: pdm_user  
      MYSQL_PASSWORD: ${DB_PASSWORD?未设置应用密码}  
    networks:  
      - pdm_shared_network  
    healthcheck:  
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$${MYSQL_ROOT_PASSWORD}"]  
 
  pdm-frontend:  
    image: node:18  
    working_dir: /app  
    env_file: .env  
    user: "1000:1000"
    volumes:  
      - ./src:/app/src  
      - node_modules:/app/node_modules  
    depends_on:  
      jx-mysql:  
        condition: service_healthy  
      api-service:  
        condition: service_started  
    networks:  
      - pdm_shared_network  
  
  api-service:  
    build:  
      context: /mnt/pdm_shared/api  # 显式指定绝对路径  
      dockerfile: Dockerfile
    image: pdm-api:${TAG:-latest}  
    env_file: .env 
    user: "1000:1000"
    ports:  
      - "3000:3000"  
    networks:  
      - pdm_shared_network 
 
volumes:  
  mysql_data:  
  node_modules:  
 
networks:  
  pdm_shared_network:  
    driver: bridge  